version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    environment:
      #https://www.elastic.co/guide/en/elasticsearch/reference/current/_memory_lock_check.html
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - ELASTIC_PASSWORD=123456
      - xpack.security.enabled=true
    ports:
      - 9200:9200
    networks: [ 'stack' ]


networks:
  stack: { }
